---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"

# Configure Apache.
- name: Configure Apache.
  include_tasks: "configure-{{ ansible_os_family }}.yml"

#- name: Ensure Apache has selected state and enabled on boot.
#  service:
#    name: "{{ apache_service }}"
#    state: "{{ apache_state }}"
#    enabled: true