---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: "setup-{{ ansible_os_family }}.yml"

# Configure Apache.
- name: Configure Apache.
  include_tasks: "configure-{{ ansible_os_family }}.yml"

# Configure Apache Error Sites.
- name: Configure Apache Error Sites.
  include_tasks: "configure-error_sites.yml"
  when: apache_error_site_manage
